[project]
name = "DPUG Demo"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
target-version = "py312"
line-length = 79
indent-width = 4

[tool.ruff.lint]
# ignore = ["F401"]
